### ISSUE TITLE
Does not pass SHA256 Test Vector Known Answer Tests (KAT)

### ISSUE THREAD

**Issue by dmwheel1** [nanpuyue/sha256#1]
There are two bugs in the implementation that prevent the KAT from passing.
First, the main compression function is implemented incorrectly. Lines 77-84 update the primary state after each of the 64 rounds of the algorithm, however this is incorrect. The state is not to be updated until AFTER all 64 rounds - see NIST FIPS 180-4 6.2.2 steps 2 and 4. In step 2, a copy of the previous round state is put into temporary variables, then the copies of the state are updated in each round in step 3. In step 4, the new state is created from the old state and the copies of the state variables (a, b, c,...).

The second problem is in the length construction. Use of the update function creates problems as a full block is not create. The final method needs to handle the length construction to input a full block into the compression function. In some cases this requires a new block to be created because there are not 65 bits leftover in the buffer. The whole final function needs to be rewritten. 

I have made both fixes in my private area and now pass the KAT tests. See the KAT tests here: https://www.di-mgt.com.au/sha_testvectors.html

**Comment by nanpuyue** [comment]
Which KAT test can't pass?

**Comment by nanpuyue** [comment]
I have added these tests:
https://github.com/nanpuyue/sha256/blob/master/tests/tests.rs

**Comment by dmwheel1** [comment]
Do the KAT tests you added pass correctly for you?

**Comment by nanpuyue** [comment]
> Do the KAT tests you added pass correctly for you?

Yes
